---
- name: Déployer le cluster Kubernetes
  hosts: all
  become: true
  pre_tasks:
    - name: Vérifier que le système est Ubuntu/Debian
      fail:
        msg: "Ce playbook requiert un système d'exploitation de type 'Debian' à exécuter. Le système actuel est '{{ ansible_os_family }}'."
      when: ansible_os_family != 'Debian'
  tasks:

    - name: Bloc de tâches pour Debian
      block:
        - name: Installer les paquets requis
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - software-properties-common
            state: present

        - name: Ajouter la clé GPG officielle de Docker
          apt_key:
            url: "https://download.docker.com/linux/ubuntu/gpg"
    
        - name: Obtenir le nom de code d'Ubuntu
          command: lsb_release -cs
          register: ubuntu_codename

        - name: Ajouter le référentiel Docker
          apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable"
            update_cache: yes

        - name: Installer Docker CE
          apt:
            name: docker-ce
            state: present

        - name: Ajouter la clé GPG de Kubernetes
          apt_key:
            url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"

        - name: Installer Kubernetes
          apt_repository:
            repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"

        - name: Installer les composants Kubernetes
          apt:
            name:
              - kubelet
              - kubeadm
              - kubectl
            state: present

    - name: Initialiser le nœud maître Kubernetes
      command: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_output
      failed_when: "'[ERROR]' in kubeadm_output.stdout or '[ERROR]' in kubeadm_output.stderr"
      when: "'Master' in group_names"
